### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by yani-rl-ai** [code-iai/iai_hsr_sim#5]
Hi @mareikep , thanks for your sharing.

I am a new HSR user. I want to know how to use this packages, i have followed the instructions, and open the HSR gazebo, but
it produced some error. please provide me some example script if you have.Thank you

**Comment by ichumuh** [comment]
Hello @ROSNovice,
I don't know what you are looking for, but this repo has nothing to do with gazebo.
It is a setup package for the HSR for our [https://github.com/code-iai/iai_naive_kinematics_sim](https://github.com/code-iai/iai_naive_kinematics_sim), which is a lightweight simulator to test motion planners.
